export const AuthErrorCode = {
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_CODE_FORMAT_INVALID: 'EMAIL_CODE_FORMAT_INVALID',
  EMAIL_CODE_EXPIRED_OR_NOT_FOUND: 'EMAIL_CODE_EXPIRED_OR_NOT_FOUND',
  EMAIL_CODE_ATTEMPTS_EXCEEDED: 'EMAIL_CODE_ATTEMPTS_EXCEEDED',
  EMAIL_CODE_INVALID: 'EMAIL_CODE_INVALID',
  AUTH_CONFIG_INVALID: 'AUTH_CONFIG_INVALID',
  SIGNUP_TOKEN_INVALID: 'SIGNUP_TOKEN_INVALID',
  SIGNUP_TOKEN_FORMAT_INVALID: 'SIGNUP_TOKEN_FORMAT_INVALID',
  SIGNUP_EMAIL_MISMATCH: 'SIGNUP_EMAIL_MISMATCH',
  SIGNUP_ALREADY_EXISTS: 'SIGNUP_ALREADY_EXISTS',
  SIGNUP_SAVE_FAILED: 'SIGNUP_SAVE_FAILED',
  USER_REPOSITORY_NOT_READY: 'USER_REPOSITORY_NOT_READY',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export type AuthErrorCodeValue =
  (typeof AuthErrorCode)[keyof typeof AuthErrorCode];
