export const TodoErrorCode = {
  TODO_REPOSITORY_NOT_READY: 'TODO_REPOSITORY_NOT_READY',
  TODO_QUERY_MONTH_INVALID: 'TODO_QUERY_MONTH_INVALID',
  TODO_CATEGORY_NOT_FOUND: 'TODO_CATEGORY_NOT_FOUND',
  TODO_CONTENT_INVALID: 'TODO_CONTENT_INVALID',
  TODO_MEMO_INVALID: 'TODO_MEMO_INVALID',
  TODO_DATE_INVALID: 'TODO_DATE_INVALID',
  TODO_SEARCH_KEYWORD_INVALID: 'TODO_SEARCH_KEYWORD_INVALID',
  TODO_UPDATE_PAYLOAD_EMPTY: 'TODO_UPDATE_PAYLOAD_EMPTY',
  TODO_REPEAT_DATE_INVALID: 'TODO_REPEAT_DATE_INVALID',
  TODO_REPEAT_TODAY_SOURCE_INVALID: 'TODO_REPEAT_TODAY_SOURCE_INVALID',
  TODO_REPEAT_TOMORROW_SOURCE_INVALID: 'TODO_REPEAT_TOMORROW_SOURCE_INVALID',
  TODO_REPEAT_TARGET_SAME_AS_SOURCE: 'TODO_REPEAT_TARGET_SAME_AS_SOURCE',
  TODO_NOT_FOUND: 'TODO_NOT_FOUND',
  TODO_CREATE_FAILED: 'TODO_CREATE_FAILED',
  TODO_LIST_FAILED: 'TODO_LIST_FAILED',
  TODO_SEARCH_FAILED: 'TODO_SEARCH_FAILED',
  TODO_COMPLETION_UPDATE_FAILED: 'TODO_COMPLETION_UPDATE_FAILED',
  TODO_UPDATE_FAILED: 'TODO_UPDATE_FAILED',
  TODO_GET_FAILED: 'TODO_GET_FAILED',
  TODO_DELETE_FAILED: 'TODO_DELETE_FAILED',
  TODO_REPEAT_TODAY_FAILED: 'TODO_REPEAT_TODAY_FAILED',
  TODO_REPEAT_TOMORROW_FAILED: 'TODO_REPEAT_TOMORROW_FAILED',
  TODO_REPEAT_NEXT_FAILED: 'TODO_REPEAT_NEXT_FAILED',
} as const;

export type TodoErrorCodeValue =
  (typeof TodoErrorCode)[keyof typeof TodoErrorCode];
