export const CtgErrorCode = {
  CATEGORY_REPOSITORY_NOT_READY: 'CATEGORY_REPOSITORY_NOT_READY',
  CATEGORY_NAME_INVALID: 'CATEGORY_NAME_INVALID',
  CATEGORY_LIMIT_EXCEEDED: 'CATEGORY_LIMIT_EXCEEDED',
  CATEGORY_NAME_DUPLICATED: 'CATEGORY_NAME_DUPLICATED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ORDER_INVALID: 'CATEGORY_ORDER_INVALID',
  CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',
  CATEGORY_ORDER_UPDATE_FAILED: 'CATEGORY_ORDER_UPDATE_FAILED',
} as const;

export type CtgErrorCodeValue =
  (typeof CtgErrorCode)[keyof typeof CtgErrorCode];
