export const RtnErrorCode = {
  ROUTINE_REPOSITORY_NOT_READY: 'ROUTINE_REPOSITORY_NOT_READY',
  ROUTINE_CATEGORY_NOT_FOUND: 'ROUTINE_CATEGORY_NOT_FOUND',
  ROUTINE_NAME_INVALID: 'ROUTINE_NAME_INVALID',
  ROUTINE_DATE_INVALID: 'ROUTINE_DATE_INVALID',
  ROUTINE_DATE_RANGE_INVALID: 'ROUTINE_DATE_RANGE_INVALID',
  ROUTINE_REPEAT_DAYS_REQUIRED: 'ROUTINE_REPEAT_DAYS_REQUIRED',
  ROUTINE_REPEAT_DATES_REQUIRED: 'ROUTINE_REPEAT_DATES_REQUIRED',
  ROUTINE_ALARM_TIME_INVALID: 'ROUTINE_ALARM_TIME_INVALID',
  ROUTINE_TODO_DATES_EMPTY: 'ROUTINE_TODO_DATES_EMPTY',
  ROUTINE_UPDATE_PAYLOAD_EMPTY: 'ROUTINE_UPDATE_PAYLOAD_EMPTY',
  ROUTINE_ORDER_INVALID: 'ROUTINE_ORDER_INVALID',
  ROUTINE_NOT_FOUND: 'ROUTINE_NOT_FOUND',
  ROUTINE_CREATE_FAILED: 'ROUTINE_CREATE_FAILED',
  ROUTINE_GET_FAILED: 'ROUTINE_GET_FAILED',
  ROUTINE_UPDATE_FAILED: 'ROUTINE_UPDATE_FAILED',
  ROUTINE_DELETE_FAILED: 'ROUTINE_DELETE_FAILED',
  ROUTINE_ORDER_UPDATE_FAILED: 'ROUTINE_ORDER_UPDATE_FAILED',
  ROUTINE_LIST_FAILED: 'ROUTINE_LIST_FAILED',
} as const;

export type RtnErrorCodeValue =
  (typeof RtnErrorCode)[keyof typeof RtnErrorCode];
