export const NtfErrorCode = {
  NTF_TOKEN_REPOSITORY_NOT_READY: 'NTF_TOKEN_REPOSITORY_NOT_READY',
  NTF_TOKEN_PLATFORM_INVALID: 'NTF_TOKEN_PLATFORM_INVALID',
  NTF_TOKEN_NOT_FOUND: 'NTF_TOKEN_NOT_FOUND',
  NTF_TOKEN_SAVE_FAILED: 'NTF_TOKEN_SAVE_FAILED',
  NTF_TOKEN_REMOVE_FAILED: 'NTF_TOKEN_REMOVE_FAILED',
  PUSH_SEND_FAILED: 'PUSH_SEND_FAILED',
} as const;

export type NtfErrorCodeValue =
  (typeof NtfErrorCode)[keyof typeof NtfErrorCode];
